/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Eric' at '25.08.16 19:22' with Gradle 2.13
 *
 * @author Eric, @date 25.08.16 19:22
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
